[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@uniswap/=lib/solidity-lib/src/libraries",
    "@core/=lib/v2-core/src",
]
